application: grafiddle
version: 1
runtime: python27
api_version: 1
threadsafe: yes
module: default

handlers:
- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: static/\1
  upload: static/(.*\.ico)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)


- url: .*
  script: grafiddle.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
